services:
  postgres:
   image: postgres
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Car
   ports:
     - 5432:5432
   volumes:
     - pgdata:/var/lib/postresql/data  
volumes:
  pgdata:     
