services:
  postgres:
   image: postgres
   environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Car
   ports:
     - 5432:5432
   volumes:
     - pgdata:/var/lib/postresql/data  
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
volumes:
  pgdata:    
  mongodata: 
